### ISSUE TITLE
botan result generation

### ISSUE THREAD

**Issue by baentsch** [IETF-Hackathon/pqc-certificates#67]
When reading through [the results generation code in botan](https://github.com/IETF-Hackathon/pqc-certificates/blob/6789aff996b90f69b3b22545e39f0a211a56f367/providers/botan/Makefile#L148-L149) it somehow created the impression of reporting CSV verification results in the wrong order. Is this possible @janklaussner or have I misunderstood/-read?

**Comment by janklaussner** [comment]
Hi @baentsch, the botan command line interface is quite limited, it allows only to verify the complete certificate chain, passing the EE cert first and then the chain upwards to the root. I think that gives you the impression of wrong order. In the end I set all three certs to "Y" at once since I can not verify one after another. Is this what you meant?

**Comment by baentsch** [comment]
> Is this what you meant?

Yes; thanks for the explanation. I then understand and this is a non-issue.
